FROM openjdk:8-jdk-alpine
MAINTAINER Parvathy Menon  <parvathymenon75@gmail.com>
ADD target/iiht-company-service-0.0.1-SNAPSHOT.jar iiht-company-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/iiht-company-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8081